name = "Outer Circle Modpack"
author = "dashiellwascool"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd5db8b196a3fe670a6f38677348f93f064303a4d60c3832efdc382e235b3129"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
datapack-folder = "required_datapacks"
