name = "Outer Circle Modpack"
author = "dashiellwascool"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c116c2109d87667a3bbbc9ea4d54c073f117f22b16b9b59ee9dbc5b9068e54fb"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
datapack-folder = "required_datapacks"
